# Lesson 5

## Overview

- NumPy

## NumPy

Vectors/arrays/matrices in Python.

In [1]:
import numpy as np

In [2]:
a = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [30]:
b = np.array(a)

In [7]:
b * b

array([[ 1,  4],
       [ 9, 16]])

In [8]:
b @ b

array([[ 7, 10],
       [15, 22]])

In [10]:
np.linalg.inv(b) @ b

array([[1.00000000e+00, 0.00000000e+00],
       [2.22044605e-16, 1.00000000e+00]])

### zeros/ones

In [36]:
a = np.ones(100)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [39]:
a = np.zeros((5, 10))
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### Accessing elements/slicing/indexing

In [12]:
a[0][0]

1

In [13]:
b[0, 0]

1

In [14]:
idx = (0, 0)
b[idx]

1

In [15]:
a[idx]

TypeError: list indices must be integers or slices, not tuple

In [22]:
a[:1]

[[1, 2]]

In [31]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
b[:, [0, 2]][[0, 2], :]

array([[1, 3],
       [7, 9]])

In [53]:
a = rng.normal(size=1000)
b = rng.integers(1000, size=50)

In [54]:
b

array([854,  55, 721, 913, 582, 439, 713, 117, 541, 820, 156, 623, 870,
       966, 450, 282, 695, 531, 311, 678, 634, 645, 638, 191, 864, 611,
       780,  71, 855, 821, 675,  97, 334, 291, 375, 484, 908, 241,  55,
       878, 874, 752, 142,  44, 140, 563, 856, 566, 142, 274])

In [56]:
a[b]

array([ 0.2689581 ,  1.41934817,  1.57621281,  1.139808  , -1.76639489,
        0.81610715,  0.38888301,  1.71726308,  1.14546214,  0.8108156 ,
       -0.67623437, -1.41618068, -0.60233814,  0.56134346, -0.35607535,
       -0.98763303,  0.65829702,  1.63569133, -0.01772804,  0.19893244,
       -1.54752077, -0.31806732,  0.14708579,  0.08111794, -0.6938663 ,
        0.26720002,  0.03590914, -0.87805471,  2.37575881, -2.2908119 ,
        0.88363284,  1.46243824, -0.17557353, -0.49139499, -0.69848635,
       -0.47201708, -0.85016032, -0.0994117 ,  1.41934817, -0.02496758,
        0.97252838,  0.26191014,  0.03688618, -0.58286632,  0.2434175 ,
       -0.92525986, -1.0388805 , -1.73462436,  0.03688618,  0.5394642 ])

### Transpose

In [39]:
np.transpose(b, [1, 0])

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### Tile and repeat

In [46]:
c = np.arange(3)
c

array([0, 1, 2])

In [49]:
np.tile(c, 3)

array([0, 1, 2, 0, 1, 2, 0, 1, 2])

In [51]:
np.tile(c, (3, 2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [50]:
np.repeat(c, 3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [52]:
np.repeat(c, (1, 2, 3))

array([0, 1, 1, 2, 2, 2])

### Broadcasting

In [56]:
c2 = np.tile(c, (3, 1))
c2

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [57]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
c2 * b

array([[ 0,  2,  6],
       [ 0,  5, 12],
       [ 0,  8, 18]])

In [64]:
c[None, :] * b

array([[ 0,  2,  6],
       [ 0,  5, 12],
       [ 0,  8, 18]])

In [66]:
c2.T * b

array([[ 0,  0,  0],
       [ 4,  5,  6],
       [14, 16, 18]])

In [67]:
c[:, None] * b

array([[ 0,  0,  0],
       [ 4,  5,  6],
       [14, 16, 18]])

In [69]:
c

array([0, 1, 2])

In [79]:
c.shape

(3,)

In [91]:
c[:, None] + c[None, :]

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

### diff

In [30]:
a = rng.normal(size=100000)
a

array([-0.63772837, -0.26732566, -1.21791619, ...,  0.1078897 ,
       -0.31508546,  1.53632125])

In [31]:
%%timeit
a[1:] - a[: -1]

26.7 µs ± 82.2 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [32]:
%%timeit
np.diff(a)

28.7 µs ± 295 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


### cumsum

In [33]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [34]:
np.cumsum(a)

array([ 0,  1,  3,  6, 10])

### argmin/argmax/argsort

In [40]:
a = rng.normal(size=100)

In [41]:
a.argmax()

75

In [49]:
np.argmax([2, 2, 1])

0

In [42]:
a.argmin()

27

In [43]:
a.argsort()

array([27, 61,  9, 40, 43, 72, 25, 60, 54, 69, 14, 48, 51, 87,  1, 53, 16,
       91, 58,  0, 88, 79, 84, 56,  4, 78, 80, 55, 98,  2, 66,  6, 86, 52,
        8, 15, 95, 23, 81, 39, 92, 49, 85, 30, 45, 17, 34, 11, 83, 62, 93,
       71, 82, 37, 68, 74, 47, 65, 21, 35, 24, 41, 50, 77, 29, 99, 26, 36,
       19,  5, 67, 42, 63, 32, 31, 20, 73,  7, 59, 57, 64, 13, 22, 28, 96,
       70, 10, 18, 46, 89, 38, 12, 33, 90, 76, 44,  3, 94, 97, 75])

### Random generators

In [3]:
rng = np.random.default_rng(1)

In [4]:
rng.normal(size=10)

array([ 0.34558419,  0.82161814,  0.33043708, -1.30315723,  0.90535587,
        0.44637457, -0.53695324,  0.5811181 ,  0.3645724 ,  0.2941325 ])

### Sparse matrices

In [172]:
from scipy.sparse import csc_matrix

In [196]:
n = 100
n_ids = 10
ids = rng.integers(n_ids, size=n)

In [210]:
J = csc_matrix((np.ones(n), (np.arange(n), ids)), shape=(n, n_ids))

In [211]:
J.todense()

matrix([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],


In [192]:
(J.T @ J).todense()

matrix([[ 6.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0., 10.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  8., ...,  0.,  0.,  0.],
        ...,
        [ 0.,  0.,  0., ...,  7.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0., 14.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0., 11.]])

In [193]:
%%timeit
(J.T @ J)

702 ms ± 9.54 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### Bincount

In [194]:
np.bincount(ids)

array([ 6, 10,  8, ...,  7, 14, 11])

In [195]:
%%timeit
np.bincount(ids)

19.8 ms ± 388 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


### Matrix multiplication with diagonal matrices

In [5]:
def DxM(diag, m):
    '''
    Product of a diagonal and a matrix, i.e. take diag @ m.

    Arguments:
        diag (NumPy Array or float): diagonal entries or multiplicative factor
        m (NumPy Array): matrix
    '''
    if isinstance(diag, (float, int)):
        # If multiplicative factor
        if diag == 1:
            return m
        return diag * m

    # If diagonal entries
    return (diag * m.T).T

def MxD(m, diag):
    '''
    Product of a matrix and a diagonal, i.e. take m @ diag.

    Arguments:
        m (NumPy Array): matrix
        diag (NumPy Array or float): diagonal entries or multiplicative factor
    '''
    if isinstance(diag, (float, int)):
        # If multiplicative factor
        if diag == 1:
            return m
        return diag * m

    # If diagonal entries
    return m * diag

In [12]:
n = int(3 * 1e3)
a = rng.normal(size=(n, n))
b = rng.normal(size=n)

In [13]:
np.diag(b)

array([[-0.12979449,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  1.38349557,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.17053631, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.36049499,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.35106105,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.69177961]])

In [15]:
%%timeit
np.diag(b) @ a

650 ms ± 25.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [17]:
%%timeit
DxM(b, a)

4.45 ms ± 150 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [23]:
%%timeit
b[:, None] * a

4.16 ms ± 138 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [16]:
%%timeit
a @ np.diag(b)

630 ms ± 28.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [18]:
%%timeit
MxD(a, b)

5.55 ms ± 105 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [20]:
DxM(b, a)

array([[ 0.04305389, -0.02450608,  0.03333491, ...,  0.07252111,
        -0.20889637, -0.06667676],
       [-3.04643963,  0.695854  ,  1.09382668, ..., -0.3196933 ,
        -3.23805228, -0.73283361],
       [ 0.02401034,  0.11501715,  0.01543444, ..., -0.11485651,
         0.10094913,  0.11068856],
       ...,
       [-0.81180489, -0.08033079,  0.15354346, ...,  0.27811731,
         0.40886214,  0.05923034],
       [-0.03913632,  0.0205819 ,  0.38672633, ...,  0.51782762,
        -0.52494684, -0.3598065 ],
       [-0.56939833,  0.23959058,  0.88602361, ..., -1.20676408,
         0.2856753 ,  0.46799477]])

### Nonzero

In [47]:
a = rng.binomial(1, 0.5, size=100)
a

array([0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0])

In [48]:
np.argmax(a)

1

In [51]:
np.nonzero(a)[0]

array([ 1,  2,  3,  6,  7,  8,  9, 12, 13, 16, 18, 22, 23, 28, 32, 33, 34,
       37, 39, 41, 42, 43, 44, 47, 48, 49, 50, 53, 60, 61, 62, 67, 71, 74,
       78, 81, 82, 84, 86, 90, 93, 98])