# Lesson 5

## Overview

- NumPy
1. Initializing an array
2. Initialization tricks - zeros/ones
3. Mathematical operations
- Transposing multiple dimensions
4. Accessing elements/indexing/slicing
- Accessing elements/indexing
- Slicing
5. Tile and repeat
6. Broadcasting
- Cartesian products using broadcasting
7. Random generators
8. `np.diff`
9. `np.cumsum`
10. `np.argmin`/`np.argmax`/`np.argsort`
11. `np.where`/`np.nonzero`
12. `np.bincount`
13. Sparse matrices
14. Matrix multiplication with diagonal matrices

## NumPy

Vectors/arrays/matrices in Python.

In [18]:
import numpy as np

## 1. Initializing an array

In [19]:
a = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

Nested list representation

In [20]:
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

NumPy representation

In [21]:
b = np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 2. Initialization tricks - zeros/ones/empty

In [22]:
a = np.ones((5, 10))
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [23]:
a = np.zeros((5, 10))
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [24]:
a = np.empty((5, 10))
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## 3. Mathematical operations

Let `a` denote a NumPy array, then:
- `+` - element-wise addition
- `-` - element-wise subtraction
- `*` - element-wise multiplication
- `/` - element-wise division
- `**` - element-wise powers
- `@` - matrix multiplication
- `np.linalg.inv(a)` - matrix inversion
- `a.T` or `a.transpose()` or `np.transpose(a)` - matrix transpose

Mathematical operations don't work with lists

In [25]:
a * a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

But they work with NumPy arrays

In [26]:
b * b

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [27]:
b @ b

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [28]:
np.linalg.inv(b) @ b

array([[ 14.,  12.,  10.],
       [-14.,  -8.,  -2.],
       [  0.,   0.,   0.]])

### 3.1 Transposing multiple dimensions

In [29]:
np.transpose(b, [1, 0])

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## 4. Accessing elements/indexing/slicing

### 4.1 Accessing elements/indexing

With lists, access each layer separately

In [30]:
a[0][0]

np.float64(0.0)

With NumPy arrays this also works, but can also access multiple indices simultaneously

In [31]:
b[0][0]

np.int64(1)

In [32]:
b[0, 0]

np.int64(1)

Can even access indices using tuples/lists/arrays

In [33]:
idx = (0, 0)
b[idx]

np.int64(1)

This doesn't work for nested lists

In [34]:
a[idx]

np.float64(0.0)

### 4.2 Slicing

Use a comma to separate dimensions and a colon (`:`) to access an entire dimension

In [35]:
a[:1]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [36]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
b[:, [0, 2]][[0, 2], :]

array([[1, 3],
       [7, 9]])

Note that slicing can allow you to update entire arrays in-place, saving allocation time

In [38]:
b[:, :] = b.copy()

## 5. Tile and repeat

Tile stacks an entire array along a dimension (like tiles)

Repeat repeats each element of an array a given number of times, then repeats the next element, etc.

In [39]:
c = np.arange(3)
c

array([0, 1, 2])

In [40]:
np.tile(c, 3)

array([0, 1, 2, 0, 1, 2, 0, 1, 2])

In [41]:
np.tile(c, (3, 2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [42]:
np.repeat(c, 3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [43]:
np.repeat(c, (1, 2, 3))

array([0, 1, 1, 2, 2, 2])

## 6. Broadcasting

In [44]:
print(b.shape)
print(c.shape)

(3, 3)
(3,)


In [45]:
c[None, :] * b

array([[ 0,  2,  6],
       [ 0,  5, 12],
       [ 0,  8, 18]])

In [46]:
c[:, None] * b

array([[ 0,  0,  0],
       [ 4,  5,  6],
       [14, 16, 18]])

### 6.1 Cartesian products using broadcasting

In [47]:
c[:, None] + c[None, :]

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

## 7. Random generators

Allows you to specify random seeds easily

In [48]:
seed = 1
rng = np.random.default_rng(seed)

In [49]:
rng.normal(size=10)

array([ 0.34558419,  0.82161814,  0.33043708, -1.30315723,  0.90535587,
        0.44637457, -0.53695324,  0.5811181 ,  0.3645724 ,  0.2941325 ])

## 8. `np.diff`

Take element-wise differences

In [50]:
a = rng.normal(size=100000)
a

array([ 0.02842224,  0.54671299, -0.73645409, ..., -0.322686  ,
       -2.06155586, -0.70793319])

In [51]:
%%timeit
a[1:] - a[: -1]

16.6 μs ± 771 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [52]:
%%timeit
np.diff(a)

17.3 μs ± 434 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


## 9. `np.cumsum`

In [53]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [54]:
np.cumsum(a)

array([ 0,  1,  3,  6, 10])

## 10. `np.argmin`/`np.argmax`/`np.argsort`

In [55]:
a = rng.normal(size=100)

In [56]:
a.argmax()

np.int64(79)

In [57]:
np.argmax([2, 2, 1])

np.int64(0)

In [58]:
a.argmin()

np.int64(3)

In [59]:
a.argsort()

array([ 3, 70, 66, 74, 31, 89, 65, 48, 68, 29, 30, 38, 96, 72,  7, 73, 43,
        2, 22, 33, 14,  0, 67, 34, 69, 95, 85, 83, 71, 28, 44, 77, 55, 15,
       19, 54, 49, 10, 64, 17, 36, 40,  9, 61, 46, 62, 47, 20, 88, 45, 21,
       81, 76,  5, 82, 60, 86, 58, 42, 25, 26, 97, 80, 53, 32, 11, 24, 41,
       13, 16, 87, 63, 12, 90, 98, 50, 78,  4, 37, 99,  8, 92, 56, 35, 52,
       18, 59, 84,  1, 39, 94, 51, 57, 23, 27, 75, 93, 91,  6, 79])

## 11. `np.where`/`np.nonzero`

Briefly discussed in lecture 2 - find the indices where some condition holds

Supposedly `np.nonzero` is slightly faster

In [60]:
list2 = ['a', 'b', 'c', 'a']
print(list2.index('a'))

0


In [61]:
np.nonzero((np.array(list2) == 'a').astype(int))[0]

array([0, 3])

In [62]:
np.where(np.array(list2) == 'a')[0]

array([0, 3])

## 12. `np.bincount`

Groupby-sum in NumPy

In [63]:
n = 100
n_ids = 10
ids = rng.integers(n_ids, size=n)

In [64]:
np.bincount(ids)

array([10,  8,  7, 13,  5, 13,  9, 15, 14,  6])

In [65]:
%%timeit
np.bincount(ids)

387 ns ± 3.39 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [67]:
import pandas as pd
pd.DataFrame({'id': ids}).groupby('id').size()

id
0    10
1     8
2     7
3    13
4     5
5    13
6     9
7    15
8    14
9     6
dtype: int64

In [68]:
%%timeit
pd.DataFrame({'id': ids}).groupby('id').size()

117 μs ± 8.69 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


## 13. Sparse matrices

In [70]:
from scipy.sparse import csc_matrix

In [71]:
J = csc_matrix((np.ones(n), (np.arange(n), ids)), shape=(n, n_ids))

In [72]:
J.todense()

matrix([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],


In [73]:
(J.T @ J).todense()

matrix([[10.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  8.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  7.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0., 13.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  5.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0., 13.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  9.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0., 15.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 14.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  6.]])

In [193]:
%%timeit
(J.T @ J)

702 ms ± 9.54 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## 14. Matrix multiplication with diagonal matrices

In [74]:
n = int(3 * 1e3)
a = rng.normal(size=(n, n))
b = rng.normal(size=n)

In [75]:
np.diag(b)

array([[ 0.39764678,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        , -0.14556918,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        , -1.25757697, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.36896037,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
        -0.99112756,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.4753226 ]])

In [76]:
%%timeit
np.diag(b) @ a

122 ms ± 10.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [77]:
%%timeit
b[:, None] * a

8.23 ms ± 60.3 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [78]:
%%timeit
a @ np.diag(b)

114 ms ± 1.71 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [79]:
%%timeit
b[None, :] * a

8.33 ms ± 99.7 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
